name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-single-buildx-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-single-buildx
    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: test/image:${{ github.sha }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
    - name: Move cache
      run: rm -rf /tmp/.buildx-cachev && mv /tmp/.buildx-cache-new /tmp/.buildx-cache
